version: '3'

services:
  builder:
    container_name: packaging-debian-10
    image: ilmuflone/packaging-debian-10:0.1.0
    volumes:
      - ./dependencies:/dependencies:ro
      - ./output:/output
      - ./sources:/source-ro:ro

